In [3]:
import numpy as np

In [4]:
li = np.array([10, 20, 30, 40])

In [5]:
li

array([10, 20, 30, 40])

In [6]:
li = np.array([10, 20, 'amar', 40])

In [7]:
print(li)

['10' '20' 'amar' '40']


In [8]:
len(li)

4

In [9]:
type(li)

numpy.ndarray

In [10]:
li = np.array((10, 20, 'amar', 40))

In [11]:
print(li)

['10' '20' 'amar' '40']


In [12]:
li = np.array({10, 20, 'amar', 40})

In [13]:
print(li)

{40, 10, 20, 'amar'}


In [14]:
val =np.array(10)

In [15]:
val

array(10)

In [16]:
arr = np.array([10,20,30])

In [17]:
print(arr)

[10 20 30]


In [19]:
arr2 = np.array([[10,20, 30], [40,50, 60]])

In [20]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr2 = np.array([[10,20, 30], [40,50, 60]],[[4,5, 30], [40,50, 60]])