In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'id':[10],'name':['Amarnath']})

In [4]:
df

id      name
0  10  Amarnath

In [5]:
df = pd.DataFrame({'id':[10, 20],'name':['Amarnath', 'Raj']})

In [6]:
df

id      name
0  10  Amarnath
1  20       Raj

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      2 non-null      int64 
 1   name    2 non-null      object
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [10]:
df.describe()

id
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [ ]:
df

In [11]:
d = {'a': 1, 'b': 2, 'c': 3}

In [12]:
d

{'a': 1, 'b': 2, 'c': 3}

In [13]:
ser = pd.Series(data=d, index=['a', 'b', 'c'])

In [14]:
type(ser)

pandas.core.series.Series

In [15]:
ser.values

array([1, 2, 3])

In [16]:
ser.min

<bound method NDFrame._add_numeric_operations.<locals>.min of a    1
b    2
c    3
dtype: int64>

In [17]:
ser.max

<bound method NDFrame._add_numeric_operations.<locals>.max of a    1
b    2
c    3
dtype: int64>

In [18]:
ser['a']

1

In [19]:
ser['b']

2

In [20]:
# 1 dimensional data, you can always use series

In [21]:
# Python array..

In [22]:
# Pandas series more advantage than python list

In [23]:
a = pd.Series([10, 20, 33,5555, 700])

In [24]:
a

0      10
1      20
2      33
3    5555
4     700
dtype: int64

In [25]:
type(a)

pandas.core.series.Series

In [26]:
a.values

array([  10,   20,   33, 5555,  700])

In [27]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
type(a.values)

numpy.ndarray

In [29]:
b = pd.Series([641019,641020,641022], index=['Blr South','Mysore', 'Hyder'])

In [30]:
b

Blr South    641019
Mysore       641020
Hyder        641022
dtype: int64

# Pandas Series vs Builtin python list

In [31]:
code = pd.Series({'Blr':655566, 'Hyder':123232})

In [32]:
code

Blr      655566
Hyder    123232
dtype: int64

In [33]:
code.keys()

Index(['Blr', 'Hyder'], dtype='object')

In [34]:
'Blr' in code

True

In [35]:
'Chennai' in code

False

In [36]:
code.values

array([655566, 123232])

In [37]:
code.axes[0]

Index(['Blr', 'Hyder'], dtype='object')

In [42]:
code.axes[0][1]

'Hyder'

In [39]:
code['Blr']

655566

# Series with .loc and .iloc

In [43]:
animals = pd.Series(['donkey', 'dog', 'cat'], index=[1, 2, 3])

In [44]:
animals

1    donkey
2       dog
3       cat
dtype: object

In [45]:
animals.loc[1]

'donkey'

In [46]:
animals.iloc[1]

'dog'

In [50]:
animals.iloc[1:3]

2    dog
3    cat
dtype: object

In [51]:
animals.loc[1:3]

1    donkey
2       dog
3       cat
dtype: object

In [52]:
animals.iloc[-1]

'cat'

In [53]:
animals.iloc[-2]

'dog'

In [54]:
animals.iloc[-1:-4]

Series([], dtype: object)

In [55]:
animals.iloc[-1:1]

Series([], dtype: object)

In [56]:
animals.iloc[-1:]

3    cat
dtype: object

In [57]:
animals.iloc[-1:-3]

Series([], dtype: object)

# Queries with pandas

In [66]:
df = pd.read_csv('https://raw.githubusercontent.com/amarnathresearch/deloittepython/master/telecom_churn.csv')

In [64]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [67]:
df = pd.read_csv('https://raw.githubusercontent.com/amarnathresearch/deloittepython/master/iris.csv')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [70]:
setosa = df[df['species'] == 0]

In [71]:
setosa

sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
5            5.4          3.9           1.7          0.4        0
6            4.6          3.4           1.4          0.3        0
7            5.0          3.4           1.5          0.2        0
8            4.4          2.9           1.4          0.2        0
9            4.9          3.1           1.5          0.1        0
10           5.4          3.7           1.5          0.2        0
11           4.8          3.4           1.6          0.2        0
12           4.8          3.0           1.4          0.1        0
13           4.3          3.0           1.1          0.1        0
14           5.8          4.0           1.2          0.2        0
15           5.7          4.4           1.5          0.4        0
16           5.4          3.9           1.3          0.4        0
17           5.1          3.5           1.4          0.3        0
18           5.7          3.8           1.7          0.3        0
19           5.1          3.8           1.5          0.3        0
20           5.4          3.4           1.7          0.2        0
21           5.1          3.7           1.5          0.4        0
22           4.6          3.6           1.0          0.2        0
23           5.1          3.3           1.7          0.5        0
24           4.8          3.4           1.9          0.2        0
25           5.0          3.0           1.6          0.2        0
26           5.0          3.4           1.6          0.4        0
27           5.2          3.5           1.5          0.2        0
28           5.2          3.4           1.4          0.2        0
29           4.7          3.2           1.6          0.2        0
30           4.8          3.1           1.6          0.2        0
31           5.4          3.4           1.5          0.4        0
32           5.2          4.1           1.5          0.1        0
33           5.5          4.2           1.4          0.2        0
34           4.9          3.1           1.5          0.1        0
35           5.0          3.2           1.2          0.2        0
36           5.5          3.5           1.3          0.2        0
37           4.9          3.1           1.5          0.1        0
38           4.4          3.0           1.3          0.2        0
39           5.1          3.4           1.5          0.2        0
40           5.0          3.5           1.3          0.3        0
41           4.5          2.3           1.3          0.3        0
42           4.4          3.2           1.3          0.2        0
43           5.0          3.5           1.6          0.6        0
44           5.1          3.8           1.9          0.4        0
45           4.8          3.0           1.4          0.3        0
46           5.1          3.8           1.6          0.2        0
47           4.6          3.2           1.4          0.2        0
48           5.3          3.7           1.5          0.2        0
49           5.0          3.3           1.4          0.2        0

In [73]:
virginica = df[df['species'] > 1]

In [74]:
virginica_notnull = df[df['species'] > 1].notnull()

In [76]:
len(virginica_notnull)

50

In [79]:
virginica_isnull = df[df['species'] > 1].isnull()

In [80]:
len(virginica_isnull)

50

In [81]:
virginica.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 100 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     int64  
dtypes: float64(4), int64(1)
memory usage: 2.3 KB


In [82]:
# Sum function

In [83]:
# max function

In [84]:
# min function

# Grouping

In [89]:
setosa.groupby("sepal_width")["petal_width"]

In [90]:
# If there is null values in your file

In [91]:
# df.dropna()

In [ ]:
setosa

# Concatenation

In [92]:
df1 = pd.DataFrame({'id':[10],'name':['Amarnath']})

In [93]:
df2 = pd.DataFrame({'id':[20],'name':['Raj']})

In [94]:
output = pd.concat([df1, df2])

In [95]:
output

id      name
0  10  Amarnath
0  20       Raj